build:
  only:
    - master
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/knows/projects/i-learn/skos-api:latest .
    - docker push $CI_REGISTRY/knows/projects/i-learn/skos-api:latest